"use client";

import { useMemo, useState } from "react";

type RepositorySnapshot = {
  slug: string;
  name: string;
  description: string;
  domain: string;
  stack: string[];
  relation: string;
  available: boolean;
  score: number | null;
  grade: string | null;
  claims: number;
  contradictions: number;
  findings: number;
};

type Filter = "all" | "healthy" | "attention" | "offline";

function statusOf(repository: RepositorySnapshot): Filter {
  if (!repository.available || repository.score === null) return "offline";
  return repository.contradictions === 0 && repository.score >= 80
    ? "healthy"
    : "attention";
}

export function PortfolioExplorer({
  repositories,
}: {
  repositories: RepositorySnapshot[];
}) {
  const [filter, setFilter] = useState<Filter>("all");
  const [selected, setSelected] = useState(repositories[0]?.slug ?? "");

  const visible = useMemo(
    () =>
      filter === "all"
        ? repositories
        : repositories.filter((repository) => statusOf(repository) === filter),
    [filter, repositories],
  );

  const focused =
    repositories.find((repository) => repository.slug === selected) ??
    repositories[0];

  function applyFilter(value: Filter) {
    setFilter(value);
    const nextVisible =
      value === "all"
        ? repositories
        : repositories.filter((repository) => statusOf(repository) === value);
    if (!nextVisible.some((repository) => repository.slug === selected)) {
      setSelected(nextVisible[0]?.slug ?? "");
    }
  }

  return (
    <section className="ecosystem-section shell" id="ecosystem">
      <div className="ecosystem-heading">
        <div>
          <span className="section-index">03 / Connected ecosystem</span>
          <h2>A portfolio that proves how its projects fit together.</h2>
        </div>
        <p>
          This is a real local snapshot generated by Armonia. Scores describe
          repository consistency—not popularity, commercial value or code quality.
        </p>
      </div>

      <div className="portfolio-toolbar" role="toolbar" aria-label="Filter repositories">
        {(
          [
            ["all", "All"],
            ["healthy", "In harmony"],
            ["attention", "Needs attention"],
            ["offline", "Not scanned"],
          ] as const
        ).map(([value, label]) => (
          <button
            key={value}
            className={filter === value ? "active" : ""}
            type="button"
            aria-pressed={filter === value}
            onClick={() => applyFilter(value)}
          >
            {label}
            <span>
              {value === "all"
                ? repositories.length
                : repositories.filter(
                    (repository) => statusOf(repository) === value,
                  ).length}
            </span>
          </button>
        ))}
      </div>

      <div className="portfolio-layout">
        <div className="repository-list" aria-live="polite">
          {visible.map((repository, index) => {
            const status = statusOf(repository);
            return (
              <button
                type="button"
                className={`repository-card ${selected === repository.slug ? "selected" : ""}`}
                key={repository.slug}
                onClick={() => setSelected(repository.slug)}
              >
                <span className="repo-index">{String(index + 1).padStart(2, "0")}</span>
                <span className="repo-main">
                  <span className="repo-title-line">
                    <strong>{repository.name}</strong>
                    <span className={`status-dot status-${status}`} aria-label={status} />
                  </span>
                  <span className="repo-domain">{repository.domain}</span>
                  <span className="repo-description">{repository.description}</span>
                  <span className="repo-stack">
                    {repository.stack.map((item) => (
                      <i key={item}>{item}</i>
                    ))}
                  </span>
                </span>
                <span className="repo-score">
                  <strong>{repository.score ?? "—"}</strong>
                  <small>{repository.grade ?? "offline"}</small>
                </span>
              </button>
            );
          })}
          {visible.length === 0 && (
            <div className="empty-state">No repositories match this view.</div>
          )}
        </div>

        {focused && (
          <aside className="repository-detail" aria-label={`${focused.name} evidence summary`}>
            <div className="detail-topline">
              <span>Selected node</span>
              <span>{focused.available ? "snapshot available" : "source unavailable"}</span>
            </div>
            <div className="detail-score">
              <strong>{focused.score ?? "—"}</strong>
              <div>
                <span>Harmony score</span>
                <small>{focused.grade ? `Grade ${focused.grade}` : "Awaiting scan"}</small>
              </div>
            </div>
            <div className="score-track" aria-hidden="true">
              <span style={{ width: `${focused.score ?? 0}%` }} />
            </div>
            <dl className="detail-metrics">
              <div><dt>{focused.claims}</dt><dd>claims</dd></div>
              <div><dt>{focused.contradictions}</dt><dd>conflicts</dd></div>
              <div><dt>{focused.findings}</dt><dd>findings</dd></div>
            </dl>
            <div className="relationship-card">
              <span>Relationship to Armonia</span>
              <p>{focused.relation}</p>
            </div>
            <p className="snapshot-note">
              Generated locally from repository files. No GitHub token, stars or
              private source content are embedded in this page.
            </p>
          </aside>
        )}
      </div>
    </section>
  );
}
