name: Armonia CI

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  verify:
    uses: AleDet01/armonia/.github/workflows/reusable-ci.yml@16d4b7846a40e1ce68aa7cb06f3884670d562701
    with:
      armonia-repository: AleDet01/armonia
      armonia-ref: 16d4b7846a40e1ce68aa7cb06f3884670d562701
      manifest: .armonia/project.yaml
